package FunLanguage.types;

/*Generated by MPS */

import jetbrains.mps.lang.typechecking.aspect.TypecheckingAspect;
import jetbrains.mps.lang.coderules.aspect.CoderulesAspect;
import jetbrains.mps.lang.coderules.aspect.AbstractCoderulesManifest;

public class TypesAspectDescriptor extends TypecheckingAspect implements CoderulesAspect {

  @Override
  public AbstractCoderulesManifest createManifest() {
    return new Manifest(this);
  }

}
