package NewLanguage.types;

/*Generated by MPS */

import jetbrains.mps.lang.coderules.template.AbstractRuleTemplate;
import jetbrains.mps.lang.coderules.template.RuleTemplate;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.coderules.template.TemplateApplicationSession;
import jetbrains.mps.lang.coderules.template.RuleBuilder;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.logic.unification.MetaLogicalFactory;
import java.util.function.BiConsumer;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.coderules.template.ConstraintBuilder;
import jetbrains.mps.logic.reactor.program.ConstraintSymbol;
import jetbrains.mps.lang.coderules.template.PredicateBuilder;
import jetbrains.mps.logic.predicate.EvalExpressionPredicate;
import jetbrains.mps.lang.coderules.template.LateExpression;
import jetbrains.mps.logic.reactor.logical.LogicalContext;
import jetbrains.mps.logic.reactor.evaluation.InvocationContext;
import jetbrains.mps.logic.reactor.logical.Logical;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.logic.dataform.DataForm;
import jetbrains.mps.logic.predicate.UnificationPredicate;
import jetbrains.mps.logic.dataform.ValueRole;
import jetbrains.mps.logic.unification.LogicalUtil;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.coderules.template.ConstraintRuleTemplate;
import jetbrains.mps.logic.reactor.logical.MetaLogical;
import java.util.List;
import jetbrains.mps.lang.coderules.template.RuleTable;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.builder.SNodeBuilder;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class ConstantRules_intLiteral extends AbstractRuleTemplate<ConstantRules_intLiteral.Token> {

  public class Token implements RuleTemplate.Token {

    public Token(SNode input, TemplateApplicationSession session) {
      this.i = input;
      this.session = session;
    }

    @Override
    public Iterable<RuleBuilder> apply() {
      TemplateApplicationSession _session = session;
      ruleBuilders = ListSequence.fromList(new ArrayList<RuleBuilder>());
      new intLiteral() {
        @Override
        public void apply(TemplateApplicationSession session) {
          TypeCollector = MetaLogicalFactory.metaLogical("TypeCollector", BiConsumer.class);

          RuleBuilder builder = new RuleBuilder(session, "intLiteral", "intLiteral#0" + "_" + String.valueOf(token().i.getNodeId()).replaceAll("~", "_"), getTemplateRef(), token().i, SNodeOperations.getPointer(token().i));

          builder.appendHeadKept(new ConstraintBuilder(new ConstraintSymbol("checkAll", 0)).withArguments().toConstraint());
          builder.appendHeadKept(new ConstraintBuilder(new ConstraintSymbol("recoverAll", 1)).withArguments(rule().TypeCollector).toConstraint());
          builder.appendBody(new PredicateBuilder(EvalExpressionPredicate.EVAL_SYM).withArguments(new LateExpression<Object>() {
            public Object[] metaArgs() {
              return new Object[]{rule().TypeCollector, token().i, token().i};
            }
            public Object eval(LogicalContext _logicalContext, InvocationContext _invocationContext, Object... args) {
              Logical<BiConsumer<SNodeReference, SNode>> typedArg0 = (Logical<BiConsumer<SNodeReference, SNode>>) args[0];
              Logical<SNode> typedArg1 = (Logical<SNode>) args[1];
              SNode typedArg2 = (SNode) args[2];

              typedArg0.findRoot().value().accept(SNodeOperations.getPointer(typedArg1.findRoot().value()), createConstantIntegerType_j7rhs9_b0a0a0a0a0a2());
              return true;
            }
          }).toPredicate());

          ListSequence.fromList(ruleBuilders).addElement(builder);
        }

      }.apply(_session);
      new intLiteral1() {
        @Override
        public void apply(TemplateApplicationSession session) {
          IntType = MetaLogicalFactory.metaLogical("IntType", DataForm.class);

          RuleBuilder builder = new RuleBuilder(session, "intLiteral", "intLiteral#1" + "_" + String.valueOf(token().i.getNodeId()).replaceAll("~", "_"), getTemplateRef(), token().i, SNodeOperations.getPointer(token().i));

          builder.appendHeadKept(new ConstraintBuilder(new ConstraintSymbol("checkAll", 0)).withArguments().toConstraint());
          builder.appendBody(new PredicateBuilder(UnificationPredicate.UNI_SYM).withArguments(rule().IntType, (new MyTerms_termTable.intType_term(false) {
            public DataForm val() {
              return ValueRole.create("val", LogicalUtil.asValue(SPropertyOperations.getInteger(token().i, PROPS.value$9Utg)));
            }
          }).getTerm()).toPredicate());
          builder.appendBody(new ConstraintBuilder(new ConstraintSymbol("typeOf", 2)).withArguments(token().i, rule().IntType).toConstraint());

          ListSequence.fromList(ruleBuilders).addElement(builder);
        }

      }.apply(_session);
      new intLiteral2() {
        @Override
        public void apply(TemplateApplicationSession session) {
          TypeCollector = MetaLogicalFactory.metaLogical("TypeCollector", BiConsumer.class);
          Node = MetaLogicalFactory.metaLogical("Node", SNode.class);
          AssignedType = MetaLogicalFactory.metaLogical("AssignedType", DataForm.class);

          RuleBuilder builder = new RuleBuilder(session, "intLiteral", "intLiteral#2" + "_" + String.valueOf(token().i.getNodeId()).replaceAll("~", "_"), getTemplateRef(), token().i, SNodeOperations.getPointer(token().i));

          builder.appendHeadKept(new ConstraintBuilder(new ConstraintSymbol("typeOf", 2)).withArguments(rule().Node, rule().AssignedType).toConstraint());
          builder.appendHeadKept(new ConstraintBuilder(new ConstraintSymbol("recoverAll", 1)).withArguments(rule().TypeCollector).toConstraint());
          builder.appendBody(new PredicateBuilder(EvalExpressionPredicate.EVAL_SYM).withArguments(new LateExpression<Object>() {
            public Object[] metaArgs() {
              return new Object[]{rule().TypeCollector, rule().Node};
            }
            public Object eval(LogicalContext _logicalContext, InvocationContext _invocationContext, Object... args) {
              Logical<BiConsumer<SNodeReference, SNode>> typedArg0 = (Logical<BiConsumer<SNodeReference, SNode>>) args[0];
              Logical<SNode> typedArg1 = (Logical<SNode>) args[1];

              typedArg0.findRoot().value().accept(SNodeOperations.getPointer(typedArg1.findRoot().value()), createConstantIntegerType_j7rhs9_b0a0a0a0a2a2());
              return true;
            }
          }).toPredicate());

          ListSequence.fromList(ruleBuilders).addElement(builder);
        }

      }.apply(_session);

      return ruleBuilders;
    }

    protected Token token() {
      return this;
    }

    public abstract class intLiteral implements ConstraintRuleTemplate {

      protected intLiteral rule() {
        return this;
      }

      protected MetaLogical TypeCollector;

    }
    public abstract class intLiteral1 implements ConstraintRuleTemplate {

      protected intLiteral1 rule() {
        return this;
      }

      protected MetaLogical IntType;

    }
    public abstract class intLiteral2 implements ConstraintRuleTemplate {

      protected intLiteral2 rule() {
        return this;
      }

      protected MetaLogical TypeCollector;
      protected MetaLogical Node;
      protected MetaLogical AssignedType;

    }

    protected SNode i;
    protected List<SNode> required;
    protected List<RuleBuilder> ruleBuilders;
    protected TemplateApplicationSession session;
  }


  public ConstantRules_intLiteral(RuleTable ruleTable) {
    super(ruleTable, "intLiteral", SNodePointer.deserialize("r:9e6cb41b-3b70-499a-8027-e5d416a03df7(NewLanguage.types)/3100765949326701594"));
  }

  @Override
  public SAbstractConcept applicableConcept() {
    return CONCEPTS.IntValue$2D;
  }



  @Override
  public Token createToken(SNode input, TemplateApplicationSession session) {
    return new Token(input, session);
  }
  private static SNode createConstantIntegerType_j7rhs9_b0a0a0a0a0a2() {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.ConstantIntegerType$Mr);
    return n0.getResult();
  }
  private static SNode createConstantIntegerType_j7rhs9_b0a0a0a0a2a2() {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.ConstantIntegerType$Mr);
    return n0.getResult();
  }

  private static final class PROPS {
    /*package*/ static final SProperty value$9Utg = MetaAdapterFactory.getProperty(0xf1277323ea964c38L, 0xa5127456d3818e7aL, 0x44ee06468f8cb771L, 0x44ee06468f8cb772L, "value");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept IntValue$2D = MetaAdapterFactory.getConcept(0xf1277323ea964c38L, 0xa5127456d3818e7aL, 0x44ee06468f8cb771L, "NewLanguage.structure.IntValue");
    /*package*/ static final SConcept ConstantIntegerType$Mr = MetaAdapterFactory.getConcept(0xf1277323ea964c38L, 0xa5127456d3818e7aL, 0x6deaa97c1207a3faL, "NewLanguage.structure.ConstantIntegerType");
  }
}
