package NewLanguage.types;

/*Generated by MPS */

import jetbrains.mps.lang.coderules.program.analysis.PrincipalsAnalysis;
import jetbrains.mps.logic.reactor.program.IncrementalSpec;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import jetbrains.mps.logic.reactor.program.ConstraintSymbol;

public class PrincipalsAnalysisImpl extends PrincipalsAnalysis {

  public PrincipalsAnalysisImpl() {
  }

  @Override
  protected void doRun() {
    this.ability = IncrementalSpec.Enabled.values()[2];

    SetSequence.fromSet(this.principalCtrs).addElement(new ConstraintSymbol("main", 0));

    SetSequence.fromSet(principalCtrs).addElement(new ConstraintSymbol("checkAll", 0));
    SetSequence.fromSet(principalRulesTags).addElement("check");
    SetSequence.fromSet(principalRulesTags).addElement("main");
    SetSequence.fromSet(principalRulesTags).addElement("typeof");
  }
}
