package NewLanguage.types;

/*Generated by MPS */

import jetbrains.mps.lang.coderules.template.AbstractRuleTable;
import jetbrains.mps.lang.coderules.template.RuleTable;
import jetbrains.mps.lang.coderules.aspect.AbstractCoderulesManifest;
import java.util.Collection;
import jetbrains.mps.lang.coderules.template.RuleTemplate;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class Recover_ruleTable extends AbstractRuleTable implements RuleTable {

  protected Recover_ruleTable(AbstractCoderulesManifest manifest) {
    super(manifest);
    init();
  }

  @Override
  public String name() {
    return "Recover";
  }

  @Override
  public String fqName() {
    return "NewLanguage.types.Recover";
  }

  @Override
  public String extendedFqName() {
    return "";
  }

  @Override
  public Collection<RuleTemplate<?>> ruleTemplates() {
    return ruleTemplates;
  }

  private void init() {
    List<RuleTemplate<?>> list = ListSequence.fromList(new ArrayList<RuleTemplate<?>>());
    ListSequence.fromList(list).addElement(new Recover_recover_intType(this));
    ListSequence.fromList(list).addElement(new Recover_recover_floatType(this));
    ListSequence.fromList(list).addElement(new Recover_recover_intHoldingStringType(this));
    ListSequence.fromList(list).addElement(new Recover_recover_floatHoldingStringType(this));
    ListSequence.fromList(list).addElement(new Recover_recover_stringType(this));
    ListSequence.fromList(list).addElement(new Recover_recover_structType(this));
    this.ruleTemplates = ListSequence.fromList(list).asUnmodifiable();
  }

  private List<RuleTemplate<?>> ruleTemplates;
}
