package FunLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ArrayAccess = 0;
  public static final int Assignment = 1;
  public static final int BinaryExpr = 2;
  public static final int Comment = 3;
  public static final int ConstantArrayType = 4;
  public static final int ConstantDefinition = 5;
  public static final int ConstantFloatStringType = 6;
  public static final int ConstantFloatType = 7;
  public static final int ConstantIntStringType = 8;
  public static final int ConstantIntegerType = 9;
  public static final int ConstantLanguageType = 10;
  public static final int ConstantReference = 11;
  public static final int ConstantStringType = 12;
  public static final int CreateArray = 13;
  public static final int Definition = 14;
  public static final int DivExpr = 15;
  public static final int DotAccessExpr = 16;
  public static final int EmptyLine = 17;
  public static final int Expr = 18;
  public static final int Field = 19;
  public static final int FloatValue = 20;
  public static final int FunctionCall = 21;
  public static final int FunctionDefinition = 22;
  public static final int IntValue = 23;
  public static final int MinusExpr = 24;
  public static final int MulExpr = 25;
  public static final int New = 26;
  public static final int Parameter = 27;
  public static final int ParameterReference = 28;
  public static final int PlusExpr = 29;
  public static final int ProgramDefinition = 30;
  public static final int StringValue = 31;
  public static final int StructDefinition = 32;
  public static final int StructType = 33;
  public static final int VarDefinition = 34;
  public static final int VarReference = 35;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf1277323ea964c38L, 0xa5127456d3818e7aL);
    builder.put(0x36dd486f5dd2a5d3L, ArrayAccess);
    builder.put(0xb4b542f44358f90L, Assignment);
    builder.put(0x5d19e06d2880ecfcL, BinaryExpr);
    builder.put(0xb4b542f445429bbL, Comment);
    builder.put(0x36dd486f5dd84f56L, ConstantArrayType);
    builder.put(0x44ee06468f8cb6ceL, ConstantDefinition);
    builder.put(0x4a893c619ec571deL, ConstantFloatStringType);
    builder.put(0x73cc67b338abc1eeL, ConstantFloatType);
    builder.put(0x401e58fd5c3e9085L, ConstantIntStringType);
    builder.put(0x6deaa97c1207a3faL, ConstantIntegerType);
    builder.put(0x338399ced3406bd6L, ConstantLanguageType);
    builder.put(0x5d19e06d28801405L, ConstantReference);
    builder.put(0x6deaa97c1207a3fbL, ConstantStringType);
    builder.put(0x36dd486f5dd2a25eL, CreateArray);
    builder.put(0x338399ced3405e02L, Definition);
    builder.put(0x5d19e06d2881dc53L, DivExpr);
    builder.put(0xb4b542f44358f40L, DotAccessExpr);
    builder.put(0xb4b542f4434a1b5L, EmptyLine);
    builder.put(0x44ee06468f8cb6d1L, Expr);
    builder.put(0xb4b542f44252d60L, Field);
    builder.put(0x73cc67b338ab2d0cL, FloatValue);
    builder.put(0x338399ced3406c39L, FunctionCall);
    builder.put(0x338399ced3405e01L, FunctionDefinition);
    builder.put(0x44ee06468f8cb771L, IntValue);
    builder.put(0x5d19e06d2880ed3fL, MinusExpr);
    builder.put(0x5d19e06d2881dc52L, MulExpr);
    builder.put(0xb4b542f442ecb0cL, New);
    builder.put(0x338399ced3406c3eL, Parameter);
    builder.put(0x338399ced34431d1L, ParameterReference);
    builder.put(0x5d19e06d2880ed3eL, PlusExpr);
    builder.put(0x44ee06468f8cb6cbL, ProgramDefinition);
    builder.put(0x44ee06468f8cb76eL, StringValue);
    builder.put(0xb4b542f44252d5dL, StructDefinition);
    builder.put(0xb4b542f442cbb88L, StructType);
    builder.put(0xb4b542f444ba2f3L, VarDefinition);
    builder.put(0xb4b542f444ba339L, VarReference);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
